const starterAgents = [
  {
    agent_id: 1,
    firstname: "Carey",
    lastname: "Jones",
    phone: "310-213-0001",
    email: "cjones@rei.com",
    password: "pwd123",
  },
  {
    agent_id: 2,
    firstname: "Sam",
    lastname: "Bailey",
    phone: "310-213-0001",
    email: "sbailey@rei.com",
    password: "pwd456",
  },
  {
    agent_id: 3,
    firstname: "Carmen",
    lastname: "Sanchez",
    phone: "949-355-5899",
    email: "carmensanchezrei@gmail.com",
    password: "pwd789",
  },
  {
    agent_id: 4,
    firstname: "Olive",
    lastname: "Popeye",
    phone: "310-213-0001",
    email: "opopeye@rei.com",
    password: "pwd223",
  },
  {
    agent_id: 5,
    firstname: "Jack",
    lastname: "Sparrow",
    phone: "310-213-0001",
    email: "jsparrow@rei.com",
    password: "pwd233",
  },
  {
    agent_id: 6,
    firstname: "Donald",
    lastname: "Duck",
    phone: "310-213-0001",
    email: "dduck@rei.com",
    password: "pwd243",
  },
];
module.exports = starterAgents;
