//propertyseed.js

const starterProperties = [
    {
      address: "10234 England Ave",
      city: "Inglewood",
      state: "CA",
      zipcode: "90303",
      county: "Los Angeles",
      parcelNumber: "4030-006-003",
      yearBuilt: 1956,
      propertyType: "Single-Family",
      contact_firstname: "Ismael",
      contact_lastname: "Sherif",
    },
    {
      address: "10532 Burl Ave",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90043",
      county: "Los Angeles",
      parcelNumber: "4030-020-003",
      yearBuilt: 1956,
      propertyType: "Single-Family",
      contact_firstname: "Abel",
      contact_lastname: "Gomez",
    },
    {
      address: "319 Market St",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90043",
      county: "Los Angeles",
      parcelNumber: "4030-111-003",
      yearBuilt: 1978,
      propertyType: "Multi-Family",
      contact_firstname: "Michael",
      contact_lastname: "Aboda",
    },
    {
      address: "321 Market St",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90043",
      county: "Los Angeles",
      parcelNumber: "4030-111-004",
      yearBuilt: 1968,
      propertyType: "Multi-Family",
      contact_firstname: "Patricia",
      contact_lastname: "Grey",
      },
      {
      address: "10934 Grevillea Ave",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90043",
      county: "Los Angeles",
      parcelNumber: "4220-001-004",
      yearBuilt: 2022,
      propertyType: "Multi-Family",
      contact_firstname: "Bruno",
      contact_lastname: "Mars",
      },
      {
        address: "4541 Don Tomaso Dr ",
        city: "Los",
        state: "CA",
        zipcode: "90008",
        county: "Los Angeles",
        parcelNumber: "5027-012-010",
        yearBuilt: 1956,
        propertyType: "Single-Family",
        contact_firstname: "Jeremy",
        contact_lastname: "White",
      },
      {
        address: "10540 Burl Ave",
        city: "Los Angeles",
        state: "CA",
        zipcode: "90043",
        county: "Los Angeles",
        parcelNumber: "4030-020-003",
        yearBuilt: 1961,
        propertyType: "Mix-Use",
        contact_firstname: "Jeremy",
        contact_lastname: "White",
      },
      {
        address: "3957 Hillcrest Dr ",
        city: "Los Angeles",
        state: "CA",
        zipcode: "90008",
        county: "Los Angeles",
        parcelNumber: "5030-014-008",
        yearBuilt: 1955,
        propertyType: "Multi-Family",
        contact_firstname: "Jeremy",
        contact_lastname: "White",
      },
      {
        address: "3878 Bronson Ave ",
        city: "Los Angeles",
        state: "CA",
        zipcode: "90008",
        county: "Los Angeles",
        parcelNumber: "5033-002-018",
        yearBuilt: 1959,
        propertyType: "Multi-Family",
        contact_firstname: "Lex",
        contact_lastname: "Johnson",
        },
        {
        address: "4318 Leimert Blvd ",
        city: "Los Angeles",
        state: "CA",
        zipcode: "90008",
        county: "Los Angeles",
        parcelNumber: "5023-008-014",
        yearBuilt: 1931,
        propertyType: "Multi-Family",
        contact_firstname: "Ariella",
        contact_lastname: "Santos",
        },

];
  
  module.exports = starterProperties;
